curl -X PATCH    -H "Content-Type:application/json"  
-d 
'{
  "@type": "Individual",
  "@baseType": "Party",
  "givenName" : "TESTGIVENT1111",
  "familyName": "<EMPTY>",
  "name": "Full name",
  "individualIdentification": [
    {
      "@type": "IndividualIndeitification",
      "identificationId": "15",
      "identificiationType": "DUMMY TYPE"
    }
  ]
}'  
http://localhost:8082/partyManagement/v5/individual/500606518



