curl -X POST    -H "Content-Type:application/json"  
-d 
' {
                    "@type": "Individual",
                    "@baseType": "Party",
                    "givenName": "Newdtac",
                    "familyName": "Newtrinet",
                    "gender":"M",
                    "individualIdentification": [
                        {
                            "@type": "IndividualIdentification",
                            "identificiationType": "15"  ,
                            "identificationId": "15232342342"
                        }
                    ]
                  }' 
http://localhost:8082/partyManagement/v5/individual


            