curl -X POST    -H "Content-Type:application/json"  
-d 
'{
  "@type": "Individual",
  "@baseType": "Party",
  "givenName": "Newdtac",
  "familyName": "Newtrinet",
  "individualIdentification": [
      {
        "@type": "IndividualIdentification",
        "identificiationType": "15"  ,
        "identificationId": "15232342342"
      }
    ],
    "contactMedium": [{}]
}'  
http://localhost:8082/partyManagement/v5/individual



