---
apiVersion: zalando.org/v1
kind: ClusterKopfPeering
metadata:
  name: dependentapi
---
apiVersion: zalando.org/v1
kind: KopfPeering
metadata:
  namespace: {{ .Release.Namespace }}
  name: dependentapi
---
