{{- if .Values.createPeering -}}
---
apiVersion: zalando.org/v1
kind: ClusterKopfPeering
metadata:
  name: default
  labels:
    {{- include "controller.labels" . | nindent 4 }}
---
apiVersion: zalando.org/v1
kind: KopfPeering
metadata:
  namespace: {{ .Release.Namespace }}
  name: default
  labels:
    {{- include "controller.labels" . | nindent 4 }}
---
{{- end }}