# Source: partymanagement/templates/TMF632_component.yaml
apiVersion: oda.tmforum.org/v1alpha4
kind: component
metadata:
  name: test-tmf632poc
  labels:
    oda.tmforum.org/componentName: test-tmf632poc
spec:
  type: Party management
  functionalBlock: NOM
  publicationDate: 2024-11-30T00:00:00.000Z
  status: specified
  version: 0.0.1
  description: "POC Partymanagement with TMF632 ODA-Component from Open-API reference implementation."
  maintainers:
  - email: ChailucK@truecorp.co.th
    name: Chailuck K
  owners:
  - email: ChailucK@truecorp.co.th
    name: Chailuck K
  coreFunction:
    exposedAPIs: 
    - id: TMF632
      version: v5.0.0
      name: party-management-api
      implementation: test-partymanagmentapi
      apitype: openapi
      required: true
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF632_v5.0.0.swagger.json
      path: /test-tmf632poc/tmf-api/productInventory/v5
      developerUI: /test-tmf632poc/tmf-api/productInventory/v5/docs      
      port: 8082
      resources:
      - individual:
        - GET
        - GET/id
        - POST
        - PATCH/id
        - DELETE/id
      - organization:
        - GET
        - GET/id
        - POST
        - PATCH/id
        - DELETE/id
    dependentAPIs: 
    - name: party
      apitype: openapi        
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/ODA/TMF632_v5.0.0.swagger.json
  eventNotification:
    publishedEvents: []
    subscribedEvents: []
  managementFunction: 
    exposedAPIs: []
    dependentAPIs: []   
  security:
    controllerRole: Admin
    securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
    partyrole:
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
      implementation: test-partyroleapi
      apitype: openapi
      path: /test-tmf632poc/tmf-api/partyRoleManagement/v4
      developerUI: /test-tmf632poc/tmf-api/partyRoleManagement/v4/docs
      port: 8080
