apiVersion: v1
data:
  POSTGRES_PASSWORD: YWRtaW4xMjM=
  POSTGRES_USER: cG9zdGdyZXNhZG1pbg==
kind: Secret
metadata:
  creationTimestamp: null
  name: {{.Values.postgresql.name}}-secret
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}