apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.postgresql.name}}-pvc
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: {{.Values.postgresql.name}}-pv