apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.postgresql.name}}-pv
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  capacity:
    storage: 5Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{.Values.postgresql.pvPath}}
    
        