{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "partymanagement.serviceAccountName" . }}
  labels:
    {{- include "partymanagement.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
