apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/resource-policy": keep
  labels:
    {{- include "cert-manager-init.labels" . | nindent 4 }}
  name: {{ .Values.global.certificate.appName }}
  namespace: {{ include "cert-manager-init.namespace" . }}
spec:
  secretName: {{ .Values.global.certificate.appName }}-secret
  duration: {{ .Values.certificateDuration }}
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  commonName: {{ .Values.global.certificate.appName }}
  isCA: false
  usages:
    - digital signature
    - content commitment # replaces nonRepudiation
    - key encipherment
    - server auth
  dnsNames:
  - {{ .Values.certificate.appName }}
  - {{ printf "%s.%s" .Values.global.certificate.appName (include "cert-manager-init.namespace" .) }}
  - {{ printf "%s.%s.svc" .Values.global.certificate.appName (include "cert-manager-init.namespace" .) }}
  - {{ printf "%s.%s.svc.cluster.local" .Values.global.certificate.appName (include "cert-manager-init.namespace" .) }}
  issuerRef:
    name: {{ include "cert-manager-init.fullname" . }}-selfsigned
