CREATE TABLE cs_pmpt_regn (
asst_row_id char(15) ,
seqn serial NOT NULL,
cust_numb integer NOT NULL,
subr_numb char(12) ,
blpd_code char(2) NOT NULL,
card_numb char(19) ,
regs_flag char(1) NOT NULL,
strt_dttm TIMESTAMP(0) NOT NULL,
end_dttm TIMESTAMP(0) ,
doc_sms char(1) NOT NULL,
doc_sms_dttm TIMESTAMP(0) ,
regn_roam_retl char(1) ,
crtd_dttm TIMESTAMP(0) NOT NULL,
crtd_by char(12) NOT NULL,
last_chng_dttm TIMESTAMP(0) NOT NULL,
last_chng_by char(12) NOT NULL
)


// Oracle
CREATE TABLE cs_pmpt_regn (
asst_row_id char(15) ,
seqn numeric GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
cust_numb integer NOT NULL,
subr_numb char(12) ,
blpd_code char(2) NOT NULL,
card_numb char(19) ,
regs_flag char(1) NOT NULL,
strt_dttm TIMESTAMP(0) NOT NULL,
end_dttm TIMESTAMP(0) ,
doc_sms char(1) NOT NULL,
doc_sms_dttm TIMESTAMP(0) ,
regn_roam_retl char(1) ,
crtd_dttm TIMESTAMP(0) NOT NULL,
crtd_by char(12) NOT NULL,
last_chng_dttm TIMESTAMP(0) NOT NULL,
last_chng_by char(12) NOT NULL
)
