drop table cs_add_subr_pcn_06;
create table cs_add_subr_pcn_06 (
seqn SERIAL NOT NULL,
clnt_call_dttm TIMESTAMP(0) NOT NULL,
subr_numb VARCHAR(12) NOT NULL,
trns_stts VARCHAR(1) NOT NULL,
crtd_dttm TIMESTAMP(0) NOT NULL,
crtd_by VARCHAR(12) NOT NULL,
last_chng_dttm TIMESTAMP(0) NOT NULL,
last_chng_by VARCHAR(12) NOT NULL
);



create table "C##OMDTAC".cs_add_subr_pcn_06 (
seqn integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
clnt_call_dttm TIMESTAMP(0) NOT NULL,
subr_numb VARCHAR(12) NOT NULL,
trns_stts VARCHAR(1) NOT NULL,
crtd_dttm TIMESTAMP(0) NOT NULL,
crtd_by VARCHAR(12) NOT NULL,
last_chng_dttm TIMESTAMP(0) NOT NULL,
last_chng_by VARCHAR(12) NOT NULL
);


