CREATE TABLE cs_subr_pcn_00 (
ca_row_id char(15) ,
cust_numb integer NOT NULL,
subr_numb char(12) NOT NULL,
blpd_code char(2) NOT NULL,
subr_type char(1) ,
neo_subr_type char(1) ,
telp_type char(1) NOT NULL,
titl varchar(40) ,
frst_name varchar(80) NOT NULL,
last_name varchar(80) ,
subr_stts char(1) NOT NULL,
from_optr_code char(3) ,
mnpi_stts char(1) ,
mnpo_stts char(1) ,
frst_pkgp_code char(8) ,
pkgp_strt_date date ,
new_ppty_code char(3) ,
dpst_txtp_code char(4) ,
conx_txtp_code char(4) ,
telp_allc_type char(1) ,
hrdw_numb char(20) ,
card_numb char(19) NOT NULL,
sms_lang char(1) ,
ivr_lang char(1) ,
ussd_lang char(1) ,
cc_lang char(2) ,
deal_numb char(8) NOT NULL,
slmn_code char(5) ,
agmt_chck_flag char(1) ,
agmt_chck_date date ,
agmt_chck_by char(12) ,
frst_swon_dttm TIMESTAMP(0) ,
brth_swon_dttm TIMESTAMP(0) ,
swon_dttm TIMESTAMP(0) NOT NULL,
swon_by char(12) NOT NULL,
swon_resn_code char(8) NOT NULL,
swon_area_code char(1) ,
swof_dttm TIMESTAMP(0) ,
swof_by char(12) ,
swof_resn_code char(8) ,
rcnx_resn_code char(8) ,
leas_code char(5) ,
leas_strt_date date ,
leas_expr_date date ,
leas_acex_date date ,
pswd_flag char(1) ,
pswd char(4) ,
memb_id char(20) ,
remk varchar(255) ,
id_type char(2) ,
id_numb char(20) ,
gndr char(1) ,
occp_code char(3) ,
marl_stts char(1) ,
salr_levl char(1) ,
educ_levl smallint ,
emal_addr varchar(40) ,
vrfy_emal_dttm TIMESTAMP(0) ,
wait_emal_addr varchar(40) ,
wait_emal_dttm TIMESTAMP(0) ,
rcnx_paid_flag char(1) ,
stop_bill_flag char(1) ,
rfnd_dttm TIMESTAMP(0) ,
old_cust_numb integer ,
old_subr_numb char(12) ,
new_cust_numb integer ,
new_subr_numb char(12) ,
go_inter_flag char(1) NOT NULL,
chwr_cont_aou char(1) NOT NULL,
last_chng_dttm TIMESTAMP(0) NOT NULL,
last_chng_by char(12) NOT NULL
);