# Default values for productcatalog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Default values for productinventory.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Default values for productinventory.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

component:
  # Specifies whether a service account should be created
  id: TMFC028
  name: tmf632
  functionalBlock: NOM
  publicationDate: 2024-11-30T00:00:00.000Z
  version: "0.0.1"
  storageClassName: default
security:
  controllerRole: Admin
service:
  type: ClusterIP
  port: 8082
serviceAccount:
  # Specifies whether a service account should be created
  create: true
ingress:
  enabled: false
postgresql:
  port: 5432
  database: postgres
autoscaling:
  enabled: false

image:
  repository: chailuck/tmfecho:v2
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

api:
  image: chailuck/tmfecho:v2
  versionlabel: tmf632-2.0
